

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	
namespace Ducksoft.SOA.BL.Templates.Models
{
	using Ducksoft.SOA.Common.Contracts;
    using Ducksoft.SOA.BL.Templates.Repositories;
    
    /// <summary>
    /// Interface which is used to handle xxx data.
    /// </summary>
    public partial interface IxxxModel
    {	
    }
    
    /// <summary>
    /// Class which used to handle xxx data.
    /// </summary>
    public partial class xxxModel : IxxxModel
    {
        /// <summary>
        /// The xxxDB repository
        /// </summary>
        private readonly IxxxDBRepository xxxdbRepository;
    
        /// <summary>
        /// The logger
        /// </summary>
        private readonly ILoggingService logger;	
    
        /// <summary>
        /// Initializes a new instance of the <see cref="xxxModel" /> class.
        /// </summary>
        /// <param name="xxxdbRepository">The xxxDB repository.</param>
        /// <param name="logger">The logger.</param>
        public xxxModel(IxxxDBRepository xxxdbRepository, ILoggingService logger)
        {
            this.xxxdbRepository = xxxdbRepository;
            this.logger = logger;
        }
    }
}
	
